version: '3.9'
services:
  frontend:
    build: ./client
    ports:
      - "5000:5000"
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "7000:7000"
    dns:
      - 8.8.8.8

